# My configs
set-option -g default-shell /usr/bin/zsh
set-option -g history-limit 100000
# Set new panes to open in current directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

#vim bindings
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
# bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'


bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

bind-key -T root F1 select-window -t 0
bind-key -T root F2 select-window -t 1
bind-key -T root F3 select-window -t 2
bind-key -T root F4 select-window -t 3
bind-key -T root F5 select-window -t 4
bind-key -T root F6 select-window -t 5
bind-key -T root F7 select-window -t 6


set -g default-terminal "screen-256color"


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin "nordtheme/tmux"
set -g @plugin 'niksingh710/minimal-tmux-status'
set -g @plugin 'tmux-plugins/tmux-sidebar'
set -g @plugin 'rickstaa/tmux-notify'
set -g @plugin 'wfxr/tmux-power'

# Git status tmux
set -g status-left "#{simple_git_status}"

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Custom
# unbind C-a
# set-option -g prefix C-b
# set -g @keylocker-toggle-bind 'C-g'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'


